version: "3"
services:
  db-api:
    image: postgres:17-alpine
    shm_size: 128mb
    environment:
      POSTGRES_DB: observatorio_conocimiento
      POSTGRES_USER: observatorio_conocimiento
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db-api:/var/lib/mysql
      - ./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/1.sql

volumes:
  db-api: {}
