version: "3"
services:
  db-api:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: observatorio_conocimiento
    ports:
      - "3306:3306"
    volumes:
      - db-api:/var/lib/mysql
      - ./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/1.sql

volumes:
  db-api: {}
