spring:
  application:
    name: observatorio-conocimiento-api
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  batch:
    job:
      enabled: false

app:
  batch:
    chunk:
      size: 10

management:
  endpoints:
    web.exposure.include: 'health, metrics'
  endpoint:
    health:
      probes.enabled: true
      db:
        enabled: false
  health:
    db:
      enabled: false
