# Se sobrescriben los valores de application.yml para ejecucion con profile local
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/observatorio_conocimiento?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: observatorio_conocimiento
    password: root
